// ============================================================================
// Boardroom Pro — One-Click Professional Template Starters
// Generates rich, state-of-the-art layout objects (headers, columns, frames,
// sticky notes, device mockups, matrices) when launching a template room.
// ============================================================================

function fallbackUid(prefix = 'tpl') {
  const rand = Math.random().toString(36).slice(2, 9);
  const time = Date.now().toString(36).slice(-4);
  return `${prefix}_${rand}${time}`;
}

export function getTemplateSlugFromRoomCode(roomCode) {
  if (!roomCode || typeof roomCode !== 'string') return null;
  const lower = roomCode.toLowerCase();
  if (lower.includes('-retrospective') || lower === 'retrospective') return 'retrospective';
  if (lower.includes('-architecture') || lower === 'architecture') return 'architecture';
  if (lower.includes('-wireframe') || lower === 'wireframe') return 'wireframe';
  if (lower.includes('-codereview') || lower === 'codereview') return 'codereview';
  if (lower.includes('-brainstorm') || lower === 'brainstorm') return 'brainstorm';
  if (lower.includes('-blank') || lower === 'blank') return 'blank';
  return null;
}

export function getTemplateStarterObjects(templateSlug) {
  if (!templateSlug || templateSlug === 'blank') return [];

  const createTitleBar = (titleText) => [
    {
      type: 'rect',
      version: '6.0.0',
      id: fallbackUid('banner_bg'),
      pageId: 'page-1',
      left: 60,
      top: 40,
      width: 1160,
      height: 70,
      fill: '#f8fafc',
      stroke: '#cbd5e1',
      strokeWidth: 1,
      rx: 14,
      ry: 14,
      selectable: false,
    },
    {
      type: 'i-text',
      version: '6.0.0',
      id: fallbackUid('banner_text'),
      pageId: 'page-1',
      left: 95,
      top: 60,
      text: titleText,
      fontSize: 24,
      fontWeight: 'bold',
      fill: '#0f172a',
      fontFamily: 'Inter, system-ui, sans-serif',
      selectable: true,
    },
  ];

  switch (templateSlug) {
    case 'retrospective': {
      return [
        ...createTitleBar('🚀 Agile Sprint Retrospective · Team Alignment & Action Plan'),
        // Column 1: What Went Well
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('col_green'),
          pageId: 'page-1',
          left: 60,
          top: 135,
          width: 360,
          height: 560,
          fill: '#f0fdf4',
          stroke: '#22c55e',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('title_green'),
          pageId: 'page-1',
          left: 85,
          top: 160,
          text: 'What Went Well? 🎉',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#15803d',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_g1'),
          pageId: 'page-1',
          left: 90,
          top: 215,
          width: 300,
          text: 'Shipped the zero-latency WebSocket synchronization engine sub-14ms globally!',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          textAlign: 'left',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_g2'),
          pageId: 'page-1',
          left: 90,
          top: 360,
          width: 300,
          text: 'Great cross-functional collaboration on the UI glassmorphism redesign.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          textAlign: 'left',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },

        // Column 2: What Needs Improvement
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('col_yellow'),
          pageId: 'page-1',
          left: 460,
          top: 135,
          width: 360,
          height: 560,
          fill: '#fffbeb',
          stroke: '#f59e0b',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('title_yellow'),
          pageId: 'page-1',
          left: 485,
          top: 160,
          text: 'What Needs Improvement? 🔧',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#b45309',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_y1'),
          pageId: 'page-1',
          left: 490,
          top: 215,
          width: 300,
          text: 'We need automated edge case coverage for temporary offline network drops.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          textAlign: 'left',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_y2'),
          pageId: 'page-1',
          left: 490,
          top: 360,
          width: 300,
          text: 'Avatar cache needs optimization when joining rooms over 50 collaborators.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          textAlign: 'left',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },

        // Column 3: Action Items
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('col_blue'),
          pageId: 'page-1',
          left: 860,
          top: 135,
          width: 360,
          height: 560,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('title_blue'),
          pageId: 'page-1',
          left: 885,
          top: 160,
          text: 'Action Items & Owners ⚡',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#1d4ed8',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_b1'),
          pageId: 'page-1',
          left: 890,
          top: 215,
          width: 300,
          text: '[@Anvi] Implement exponential backoff retry loops for WebSocket reconnection by Friday.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dbeafe',
          textAlign: 'left',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_b2'),
          pageId: 'page-1',
          left: 890,
          top: 360,
          width: 300,
          text: '[@Gulu] Set up bundle size checks in GitHub Actions CI/CD pipeline.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dbeafe',
          textAlign: 'left',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
      ];
    }

    case 'architecture': {
      return [
        ...createTitleBar('⚡ System Architecture & Microservices Flowchart · Cloud Topology'),
        // Tier 1
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_client'),
          pageId: 'page-1',
          left: 100,
          top: 180,
          width: 300,
          height: 140,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_client'),
          pageId: 'page-1',
          left: 125,
          top: 215,
          text: '🖥️ Web & Mobile Clients\nReact 19 / Fabric.js / Vite\nSub-14ms Canvas Sync',
          fontSize: 16,
          fontWeight: 'bold',
          fill: '#1e40af',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Tier 2
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_gateway'),
          pageId: 'page-1',
          left: 480,
          top: 180,
          width: 320,
          height: 140,
          fill: '#f3e8ff',
          stroke: '#8b5cf6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_gateway'),
          pageId: 'page-1',
          left: 505,
          top: 215,
          text: '⚡ Edge Relay Gateway\nDual-Transport WebSocket\nGlobal Multi-Region Relay',
          fontSize: 16,
          fontWeight: 'bold',
          fill: '#6b21a8',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Tier 3 A
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_auth'),
          pageId: 'page-1',
          left: 880,
          top: 135,
          width: 300,
          height: 120,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_auth'),
          pageId: 'page-1',
          left: 905,
          top: 165,
          text: '🔒 Auth & User Directory\nGoogle OAuth & Tags\nJWT Token Verification',
          fontSize: 15,
          fontWeight: 'bold',
          fill: '#065f46',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Tier 3 B
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_state'),
          pageId: 'page-1',
          left: 880,
          top: 285,
          width: 300,
          height: 120,
          fill: '#fffbeb',
          stroke: '#f59e0b',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_state'),
          pageId: 'page-1',
          left: 905,
          top: 315,
          text: '💾 State Snapshot Store\nIn-Memory / Redis Relay\n24-Hour Room Persistence',
          fontSize: 15,
          fontWeight: 'bold',
          fill: '#92400e',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Notes
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_a1'),
          pageId: 'page-1',
          left: 480,
          top: 360,
          width: 320,
          text: '💡 Note: Edge Gateway automatically falls back to long-polling HTTP packets if corporate firewalls block raw WebSocket upgrades.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_a2'),
          pageId: 'page-1',
          left: 100,
          top: 360,
          width: 300,
          text: '📌 Client side uses local optimistic object drawing and delta modification packets.',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
      ];
    }

    case 'wireframe': {
      return [
        ...createTitleBar('🎨 UI Wireframe & Design Critique · Mobile & Desktop Flows'),
        // Mobile phone container
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('phone_bg'),
          pageId: 'page-1',
          left: 100,
          top: 140,
          width: 320,
          height: 560,
          fill: '#f8fafc',
          stroke: '#334155',
          strokeWidth: 3,
          rx: 36,
          ry: 36,
          selectable: false,
        },
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('phone_notch'),
          pageId: 'page-1',
          left: 225,
          top: 156,
          width: 70,
          height: 6,
          fill: '#94a3b8',
          stroke: '#94a3b8',
          rx: 3,
          ry: 3,
          selectable: false,
        },
        // App topbar
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_topbar'),
          pageId: 'page-1',
          left: 125,
          top: 185,
          width: 270,
          height: 50,
          fill: '#e2e8f0',
          stroke: '#cbd5e1',
          rx: 10,
          ry: 10,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_topbar_txt'),
          pageId: 'page-1',
          left: 145,
          top: 200,
          text: 'Navigation TopBar Header',
          fontSize: 14,
          fontWeight: 'bold',
          fill: '#475569',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        // Hero canvas
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_hero'),
          pageId: 'page-1',
          left: 125,
          top: 255,
          width: 270,
          height: 220,
          fill: '#cbd5e1',
          stroke: '#94a3b8',
          rx: 14,
          ry: 14,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_hero_txt'),
          pageId: 'page-1',
          left: 155,
          top: 350,
          text: 'Hero Whiteboard Canvas Preview',
          fontSize: 13,
          fontWeight: 'bold',
          fill: '#334155',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        // CTA button
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_cta'),
          pageId: 'page-1',
          left: 125,
          top: 500,
          width: 270,
          height: 56,
          fill: '#3b82f6',
          stroke: '#2563eb',
          rx: 14,
          ry: 14,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_cta_txt'),
          pageId: 'page-1',
          left: 165,
          top: 518,
          text: 'Primary CTA: New Board 🚀',
          fontSize: 15,
          fontWeight: 'bold',
          fill: '#ffffff',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Critique notes
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_w1'),
          pageId: 'page-1',
          left: 480,
          top: 150,
          width: 360,
          text: '💡 Design Critique: Make sure the Primary CTA button maintains high contrast against dark glassmorphism backgrounds!',
          fontSize: 16,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          padding: 16,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_w2'),
          pageId: 'page-1',
          left: 480,
          top: 330,
          width: 360,
          text: '🎯 UX Recommendation: Add real-time collaborator avatar badges right beside the TopBar notification bell.',
          fontSize: 16,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fbcfe8',
          padding: 16,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_w3'),
          pageId: 'page-1',
          left: 480,
          top: 510,
          width: 360,
          text: '⚡ Micro-Animation: Hovering over the card should smoothly scale and reveal action buttons.',
          fontSize: 16,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          padding: 16,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
      ];
    }

    case 'codereview': {
      return [
        ...createTitleBar('💻 Real-Time Algorithm Review & Architecture · Live Code Walkthrough'),
        // Problem container
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_prob'),
          pageId: 'page-1',
          left: 80,
          top: 140,
          width: 460,
          height: 520,
          fill: '#f8fafc',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_prob_h'),
          pageId: 'page-1',
          left: 110,
          top: 170,
          text: '📌 Problem Statement: LRU Cache Engine',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#1d4ed8',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_cr1'),
          pageId: 'page-1',
          left: 110,
          top: 220,
          width: 400,
          text: 'Design and implement a Least Recently Used (LRU) cache with O(1) time complexity for get(key) and put(key, val).\n\nRequirements:\n1. Hash Map for O(1) key lookups\n2. Doubly Linked List for O(1) eviction order\n3. Real-time multi-cursor thread safety',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#eff6ff',
          padding: 16,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },

        // Complexity container
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_comp'),
          pageId: 'page-1',
          left: 580,
          top: 140,
          width: 480,
          height: 250,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_comp_h'),
          pageId: 'page-1',
          left: 610,
          top: 170,
          text: '⚡ Complexity & Architecture Notes',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#047857',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_cr2'),
          pageId: 'page-1',
          left: 610,
          top: 220,
          width: 420,
          text: '• get(key): O(1) average lookup via Hash Map pointer\n• put(key, val): O(1) node insertion/eviction\n• Space Complexity: O(C) where C is max capacity',
          fontSize: 15,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          padding: 14,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_cr3'),
          pageId: 'page-1',
          left: 580,
          top: 420,
          width: 480,
          text: '👉 Tip: Open the "Code & Compiler" panel on the right side of the room to execute algorithms live across JavaScript, Python & C++ with real-time peer output!',
          fontSize: 16,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          padding: 16,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 14, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
      ];
    }

    case 'brainstorm': {
      return [
        ...createTitleBar('✨ Product Innovation Matrix · High-Velocity Ideation & Clustering'),
        // Q1 Top Left
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q1_box'),
          pageId: 'page-1',
          left: 60,
          top: 135,
          width: 550,
          height: 275,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q1_txt'),
          pageId: 'page-1',
          left: 85,
          top: 160,
          text: 'High Impact / Low Effort (Do First 🚀)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#065f46',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q1a'),
          pageId: 'page-1',
          left: 90,
          top: 205,
          width: 230,
          text: 'AI-powered sticky note clustering and title generator',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q1b'),
          pageId: 'page-1',
          left: 345,
          top: 205,
          width: 230,
          text: 'Instant PDF export with custom corporate watermarks',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dcfce7',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },

        // Q2 Top Right
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q2_box'),
          pageId: 'page-1',
          left: 640,
          top: 135,
          width: 550,
          height: 275,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q2_txt'),
          pageId: 'page-1',
          left: 665,
          top: 160,
          text: 'High Impact / High Effort (Strategic Plan 🎯)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#1e40af',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q2a'),
          pageId: 'page-1',
          left: 670,
          top: 205,
          width: 230,
          text: 'Voice-to-sticky note AI real-time meeting transcription',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dbeafe',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q2b'),
          pageId: 'page-1',
          left: 925,
          top: 205,
          width: 230,
          text: 'End-to-end WebRTC video chat embedded in whiteboard',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#dbeafe',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },

        // Q3 Bottom Left
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q3_box'),
          pageId: 'page-1',
          left: 60,
          top: 430,
          width: 550,
          height: 275,
          fill: '#fffbeb',
          stroke: '#f59e0b',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q3_txt'),
          pageId: 'page-1',
          left: 85,
          top: 455,
          text: 'Low Impact / Low Effort (Quick Wins ⚡)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#b45309',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q3a'),
          pageId: 'page-1',
          left: 90,
          top: 500,
          width: 230,
          text: 'Custom emoji reaction bursts on double-click',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q3b'),
          pageId: 'page-1',
          left: 345,
          top: 500,
          width: 230,
          text: 'Dark mode button inside TopBar actions',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fef9c3',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },

        // Q4 Bottom Right
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q4_box'),
          pageId: 'page-1',
          left: 640,
          top: 430,
          width: 550,
          height: 275,
          fill: '#fef2f2',
          stroke: '#ef4444',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q4_txt'),
          pageId: 'page-1',
          left: 665,
          top: 455,
          text: 'Low Impact / High Effort (Deprioritize 🗑️)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#991b1b',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'textbox',
          version: '6.0.0',
          id: fallbackUid('sticky_q4a'),
          pageId: 'page-1',
          left: 670,
          top: 500,
          width: 230,
          text: 'Legacy IE11 browser compatibility rendering engine',
          fontSize: 14,
          fill: '#1e293b',
          fontFamily: 'Inter, system-ui, sans-serif',
          backgroundColor: '#fee2e2',
          padding: 12,
          shadow: { color: 'rgba(0,0,0,0.12)', blur: 12, offsetX: 0, offsetY: 4 },
          selectable: true,
        },
      ];
    }

    default:
      return [];
  }
}
