// ============================================================================
// Boardroom Pro — One-Click Professional Template Starters
// Generates clean, spacious domain containers with titles matching each
// template name, without pre-filled text or clutter inside.
// ============================================================================

function fallbackUid(prefix = 'tpl') {
  const rand = Math.random().toString(36).slice(2, 9);
  const time = Date.now().toString(36).slice(-4);
  return `${prefix}_${rand}${time}`;
}

export function getTemplateSlugFromRoomCode(roomCode) {
  if (!roomCode || typeof roomCode !== 'string') return null;
  const lower = roomCode.toLowerCase();
  if (lower.includes('-retrospective') || lower === 'retrospective') return 'retrospective';
  if (lower.includes('-architecture') || lower === 'architecture') return 'architecture';
  if (lower.includes('-wireframe') || lower === 'wireframe') return 'wireframe';
  if (lower.includes('-codereview') || lower === 'codereview') return 'codereview';
  if (lower.includes('-brainstorm') || lower === 'brainstorm') return 'brainstorm';
  if (lower.includes('-blank') || lower === 'blank') return 'blank';
  return null;
}

export function getTemplateStarterObjects(templateSlug) {
  if (!templateSlug || templateSlug === 'blank') return [];

  const createTitleBar = (titleText) => [
    {
      type: 'rect',
      version: '6.0.0',
      id: fallbackUid('banner_bg'),
      pageId: 'page-1',
      left: 60,
      top: 40,
      width: 1160,
      height: 70,
      fill: '#f8fafc',
      stroke: '#cbd5e1',
      strokeWidth: 1,
      rx: 14,
      ry: 14,
      selectable: false,
    },
    {
      type: 'i-text',
      version: '6.0.0',
      id: fallbackUid('banner_text'),
      pageId: 'page-1',
      left: 95,
      top: 60,
      text: titleText,
      fontSize: 24,
      fontWeight: 'bold',
      fill: '#0f172a',
      fontFamily: 'Inter, system-ui, sans-serif',
      selectable: true,
    },
  ];

  switch (templateSlug) {
    case 'retrospective': {
      return [
        ...createTitleBar('🚀 Agile Sprint Retrospective · Team Alignment & Action Plan'),
        // Domain 1: What Went Well
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('col_green'),
          pageId: 'page-1',
          left: 60,
          top: 135,
          width: 360,
          height: 560,
          fill: '#f0fdf4',
          stroke: '#22c55e',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('title_green'),
          pageId: 'page-1',
          left: 85,
          top: 160,
          text: 'What Went Well? 🎉',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#15803d',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 2: What Needs Improvement
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('col_yellow'),
          pageId: 'page-1',
          left: 460,
          top: 135,
          width: 360,
          height: 560,
          fill: '#fffbeb',
          stroke: '#f59e0b',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('title_yellow'),
          pageId: 'page-1',
          left: 485,
          top: 160,
          text: 'What Needs Improvement? 🔧',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#b45309',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 3: Action Items
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('col_blue'),
          pageId: 'page-1',
          left: 860,
          top: 135,
          width: 360,
          height: 560,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('title_blue'),
          pageId: 'page-1',
          left: 885,
          top: 160,
          text: 'Action Items & Owners ⚡',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#1d4ed8',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
      ];
    }

    case 'architecture': {
      return [
        ...createTitleBar('⚡ System Architecture & Microservices Flowchart · Cloud Topology'),
        // Domain 1: Client Tier
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_client'),
          pageId: 'page-1',
          left: 80,
          top: 140,
          width: 340,
          height: 540,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_client'),
          pageId: 'page-1',
          left: 105,
          top: 165,
          text: '🖥️ Client & Presentation Tier',
          fontSize: 19,
          fontWeight: 'bold',
          fill: '#1e40af',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 2: Gateway Tier
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_gateway'),
          pageId: 'page-1',
          left: 450,
          top: 140,
          width: 360,
          height: 540,
          fill: '#f3e8ff',
          stroke: '#8b5cf6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_gateway'),
          pageId: 'page-1',
          left: 475,
          top: 165,
          text: '⚡ Edge Relay Gateway Tier',
          fontSize: 19,
          fontWeight: 'bold',
          fill: '#6b21a8',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 3: Core Directory & State Tier
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_auth'),
          pageId: 'page-1',
          left: 840,
          top: 140,
          width: 380,
          height: 540,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_auth'),
          pageId: 'page-1',
          left: 865,
          top: 165,
          text: '🔒 Core Directory & State Tier',
          fontSize: 19,
          fontWeight: 'bold',
          fill: '#065f46',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
      ];
    }

    case 'wireframe': {
      return [
        ...createTitleBar('🎨 UI Wireframe & Design Critique · Mobile & Desktop Flows'),
        // Domain 1: Mobile phone flow container
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_col'),
          pageId: 'page-1',
          left: 80,
          top: 135,
          width: 440,
          height: 560,
          fill: '#f8fafc',
          stroke: '#334155',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_col_txt'),
          pageId: 'page-1',
          left: 105,
          top: 160,
          text: '📱 Mobile App Flow Domain',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#334155',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        // Phone frame inside
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('phone_bg'),
          pageId: 'page-1',
          left: 140,
          top: 200,
          width: 320,
          height: 465,
          fill: '#ffffff',
          stroke: '#475569',
          strokeWidth: 3,
          rx: 32,
          ry: 32,
          selectable: false,
        },
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_topbar'),
          pageId: 'page-1',
          left: 165,
          top: 235,
          width: 270,
          height: 46,
          fill: '#e2e8f0',
          stroke: '#cbd5e1',
          rx: 8,
          ry: 8,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_topbar_txt'),
          pageId: 'page-1',
          left: 185,
          top: 248,
          text: 'Navigation Header Zone',
          fontSize: 14,
          fontWeight: 'bold',
          fill: '#475569',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_hero'),
          pageId: 'page-1',
          left: 165,
          top: 300,
          width: 270,
          height: 260,
          fill: '#cbd5e1',
          stroke: '#94a3b8',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_hero_txt'),
          pageId: 'page-1',
          left: 185,
          top: 420,
          text: 'Interactive Whiteboard Zone',
          fontSize: 13,
          fontWeight: 'bold',
          fill: '#334155',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('wire_cta'),
          pageId: 'page-1',
          left: 165,
          top: 580,
          width: 270,
          height: 52,
          fill: '#3b82f6',
          stroke: '#2563eb',
          rx: 12,
          ry: 12,
          selectable: true,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('wire_cta_txt'),
          pageId: 'page-1',
          left: 205,
          top: 597,
          text: 'Primary CTA Button',
          fontSize: 15,
          fontWeight: 'bold',
          fill: '#ffffff',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 2: Critique & Feedback Domain
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('critique_box'),
          pageId: 'page-1',
          left: 550,
          top: 135,
          width: 670,
          height: 560,
          fill: '#fff1f2',
          stroke: '#f43f5e',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('critique_txt'),
          pageId: 'page-1',
          left: 580,
          top: 160,
          text: '💬 Design Critique & Feedback Domain',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#be123c',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
      ];
    }

    case 'codereview': {
      return [
        ...createTitleBar('💻 Real-Time Algorithm Review & Architecture · Live Code Walkthrough'),
        // Domain 1: Problem Specifications
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_prob'),
          pageId: 'page-1',
          left: 80,
          top: 135,
          width: 530,
          height: 560,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_prob_h'),
          pageId: 'page-1',
          left: 110,
          top: 160,
          text: '📌 Problem & Algorithm Specifications',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#1d4ed8',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 2: Complexity & Architecture Domain
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('box_comp'),
          pageId: 'page-1',
          left: 640,
          top: 135,
          width: 580,
          height: 560,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('txt_comp_h'),
          pageId: 'page-1',
          left: 670,
          top: 160,
          text: '⚡ Complexity & Architecture Domain',
          fontSize: 20,
          fontWeight: 'bold',
          fill: '#047857',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
      ];
    }

    case 'brainstorm': {
      return [
        ...createTitleBar('✨ Product Innovation Matrix · High-Velocity Ideation & Clustering'),
        // Domain 1: Q1 Top Left
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q1_box'),
          pageId: 'page-1',
          left: 60,
          top: 135,
          width: 550,
          height: 275,
          fill: '#ecfdf5',
          stroke: '#10b981',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q1_txt'),
          pageId: 'page-1',
          left: 85,
          top: 160,
          text: 'High Impact / Low Effort (Do First 🚀)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#065f46',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 2: Q2 Top Right
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q2_box'),
          pageId: 'page-1',
          left: 640,
          top: 135,
          width: 550,
          height: 275,
          fill: '#eff6ff',
          stroke: '#3b82f6',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q2_txt'),
          pageId: 'page-1',
          left: 665,
          top: 160,
          text: 'High Impact / High Effort (Strategic Plan 🎯)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#1e40af',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 3: Q3 Bottom Left
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q3_box'),
          pageId: 'page-1',
          left: 60,
          top: 430,
          width: 550,
          height: 275,
          fill: '#fffbeb',
          stroke: '#f59e0b',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q3_txt'),
          pageId: 'page-1',
          left: 85,
          top: 455,
          text: 'Low Impact / Low Effort (Quick Wins ⚡)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#b45309',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },

        // Domain 4: Q4 Bottom Right
        {
          type: 'rect',
          version: '6.0.0',
          id: fallbackUid('q4_box'),
          pageId: 'page-1',
          left: 640,
          top: 430,
          width: 550,
          height: 275,
          fill: '#fef2f2',
          stroke: '#ef4444',
          strokeWidth: 2,
          rx: 16,
          ry: 16,
          selectable: false,
        },
        {
          type: 'i-text',
          version: '6.0.0',
          id: fallbackUid('q4_txt'),
          pageId: 'page-1',
          left: 665,
          top: 455,
          text: 'Low Impact / High Effort (Deprioritize 🗑️)',
          fontSize: 18,
          fontWeight: 'bold',
          fill: '#991b1b',
          fontFamily: 'Inter, system-ui, sans-serif',
          selectable: true,
        },
      ];
    }

    default:
      return [];
  }
}
